### ISSUE TITLE
Error when label already assigned

### ISSUE THREAD

**Issue by Logerfo** [pascalgn/size-label-action#8]
<details>
<summary>GitHub Action Log</summary>

Run pascalgn/size-label-action@397e38b11f1a8d4988db00d37b93ed1df6f05f41
   env:
    GITHUB_TOKEN: ***
/usr/bin/docker run --name fe0f2f6c3a91b2354cafba2df5a164264900_0aec39 --label 29fe0f --workdir /github/workspace --rm -e GITHUB_TOKEN -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/sos/sos":"/github/workspace" 29fe0f:2f6c3a91b2354cafba2df5a164264900
Changed lines: 19
Matching label: size/S
Correct label already assigned
##[error]Docker run failed with exit code 78

</details>

**Comment by pascalgn** [comment]
Thanks for the info! Unfortunately, this seems to be a result of the recent GH changes regarding actions, see for example https://github.community/t5/GitHub-API-Development-and/GitHub-Actions-quot-neutral-quot-exit-code-is-incorrectly/td-p/29051

As I see it, the special meaning of exit code 78 has been removed by GH. However, the new action implementation seems to be not stable at all yet and API and implementation could still be changing, possibly including special treatment for code 78 at some later time.

For now, you can treat "Docker run failed with exit code 78" as success/neutral, even though the GH UI reports otherwise. I will still release a new version in the following days where I will use exit code 0 for neutral exit.

**Comment by pmrcunha** [comment]
You can prevent this issue from failing your build by using the `continue-on-error` option.
Example config:
```yml
assign-size-label:
    name: Assign size label
    runs-on: ubuntu-latest
    steps:
      - name: Assign size label
        continue-on-error: true
        uses: pascalgn/size-label-action@v0.0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
